# Spring Boot application configuration
server.port=8080
application.name=SpringBootApp
author.name=Giri Sharan Reddy Pusuluru

application.description=This is a sample Spring Boot application configuration file.