name: 'Get and Cache Dependencies'
description: 'Get the Dependencies and cache them for Java Maven Project'
inputs:
  java_distribution:
    description: 'Java Distribution'
    required: true
    default: 'temurin'
  java_version:
    description: 'Java Version'
    required: true
    default: '17'
  run_command:
    description: 'Command to run after caching dependencies'
    required: false
    default: 'mvn clean package'
runs:
  using: 'composite'
  steps:
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: ${{ inputs.java_distribution }}
        java-version: ${{ inputs.java_version }}
    - name: Cache Dependencies
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
          ${{ runner.os }}-
    - name: Run Maven Build
      # if: steps.cache-dependencies.outputs.cache-hit != 'true'
      run: ${{ inputs.run_command }}
      shell: bash