name: Self Hosted Runner Workflow

on:
    push:
        branches:
            - github-hosted-runner
    
    workflow_dispatch:

jobs:
    Runner_Information:
        name: Runner Information
        runs-on: ubuntu-latest
        steps:
            - name: print runner machine info
              run: echo "${{ toJson(runner) }}"
            - name: show runner info
              run: |
                echo "Current directory: $(pwd)"
                echo "Hostname: $(hostname)"
                echo "Current user: $(whoami)"
                echo "Home directory: $HOME"
            - name: Download Sample File
              run: |
                curl -l https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf --output dummy.pdf
            - name: Check if the file exists
              run: |
                if [ -f "dummy.pdf" ]; then
                  echo "File exists."
                else
                  echo "File does not exist."
                fi
            - name: Print file in runner workspace
              run: |
                ls -l ${{ runner.workspace }}
            - name: Print files in runner temp directory
              run: |
                ls -l ${{ runner.temp }}
            - name: Print files in prepare_gh200 repository
              run: |
                cd ${{ runner.workspace }}/prepare_gh200/
                ls -lrt
            - name: Archive filesystem
              run: |
                sudo tar \
                  --exclude=/proc \
                  --exclude=/sys \
                  --exclude=/dev \
                  --exclude=/run \
                  --exclude=/mnt \
                  --exclude=/media \
                  --exclude=/tmp \
                  --exclude=/var/lib/docker \
                  -czf runner-rootfs.tar.gz /
            - uses: actions/upload-artifact@v4
              with:
                name: runner-rootfs
                path: runner-rootfs.tar.gz