name: GitHub Cache Workflow

on:
  push:
    branches:
      - github-cache
  workflow_dispatch:

jobs:
    check-m2-folder-contents:
        name: Check Maven Cache Folder Contents
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: download dependencies
              run: mvn dependency:go-offline
            - name: Check Maven Cache Folder Contents
              run: |
                echo "Checking Maven Cache Folder Contents"
                ls -la ~/.m2/repository
