name: Java Maven CI/CD Pipeline
run-name: pipeline-${{ github.workflow }}-${{ github.ref_name }}-${{ github.run_number }}-${{ github.actor }}
on:
  push:
    branches:
      - composite-actions
jobs:
    Build_Job:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: use cached-deps action to get and cache dependencies
              uses: ./.github/actions/cached-deps
              id: use-cached-deps
              with:
                java_distribution: temurin
                java_version: 17
                run_command: mvn clean package
            - name: Print Outputs from cached-deps action
              run: |
                echo "Cache Hit: ${{ steps.use-cached-deps.outputs.cache-hit }}"
                echo "Cache Key: ${{ steps.use-cached-deps.outputs.cache-key }}"
                echo "Actor: ${{ steps.use-cached-deps.outputs.actor }}"
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                name: java-maven-artifact
                path: '**/*'

    Test_Artifact_Job:
        name: Test Artifact
        runs-on: ubuntu-latest
        needs: Build_Job
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
            - name: Download Artifact
              uses: actions/download-artifact@v4
              with:
                name: java-maven-artifact
            - name: Print files in the artifact
              run: ls -lrt