name: Build

on:
  pull_request:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run build
        run: |
          echo "Running build..."
          mvn clean package
      - name: Show checked out code
        run: |
          echo "Current ref:"
          git rev-parse --abbrev-ref HEAD

          echo "Current commit:"
          git rev-parse HEAD

          echo "Properties file content:"
          cat src/main/resources/application.properties